version: "2"

services:
  grafana:
    image: grafana/grafana-enterprise:8.2.0
    ports:
      - 3000:3000

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - 9093:9093

  loki:
    image: grafana/loki:2.1.0
    ports:
      - 3100:3100

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
